version: '3'

services:
  zk:
    image: zookeeper:latest
    ports:
      - "2181:2181"
  kafka:
    image: ches/kafka
    links:
      - zk
    environment:
      KAFKA_BROKER_ID: 0
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ADVERTISED_PORT: 9092
      ZOOKEEPER_CONNECTION_STRING: zk:2181
      ZOOKEEPER_CHROOT: /broker-0
  connect:
    build: .
    image: linlo73/docker-kafka-connect-my
    links:
      - kafka
    ports:
      - "8083:8083"
    environment:
      CONNECT_BOOTSTRAP_SERVERS: kafka:9092
      CONNECT_GROUP_ID: connect-cluster-A       
    volumes:
       - "./connector:/usr/local/share/kafka/plugins/kafka-connect-jdbc"
       
volumes:
  "connector":